export const DATA = {
  name: "Bhavya Gulati",
  role: "Full-Stack Engineer",
  phone: "+91 9311796190",
  email: "bhavyagulati651@gmail.com",
  status: "OPEN TO WORK — Backend / Full-Stack Roles",
  links: [
    { label: "GitHub", url: "https://github.com/bhavyagulati123", key: "gh" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/bhavya-gulati-9434b71b4/", key: "li" },
    { label: "X (Twitter)", url: "https://x.com/bhavya_gulati1", key: "x" },
    { label: "LeetCode", url: "https://leetcode.com/u/bM2YSX9HqX/", key: "lc" },
  ],
  skills: {
    languages: ["JavaScript (ES6+)", "TypeScript", "Python", "C++", "SQL"],
    frontend: ["React.js", "Next.js", "Tailwind CSS", "HTML5", "CSS3"],
    backend: ["Node.js", "Express.js", "Django", "FastAPI", "REST APIs", "JWT", "Socket.IO"],
    databases: ["MongoDB", "PostgreSQL"],
    tools: ["Git", "GitHub", "CI/CD", "Docker", "Vercel", "Render", "Netlify"],
  },
  experience: [
    {
      date: "June 2025 — Present",
      role: "Full-Stack Engineer Intern",
      company: "Hemitaverse (Remote)",
      points: [
        "Built a custom CRM software from scratch using Next.js and Node.js — streamlined lead tracking, client management, and sales pipeline automation",
        "Implemented technical SEO strategies — structured data, meta optimization, sitemap generation, and Core Web Vitals improvements — boosting organic search visibility",
        "Led digital transformation initiatives, migrating legacy manual workflows to automated web-based systems, reducing operational overhead",
        "Designed authentication & authorization middleware using JWT and role-based access control",
        "Optimized REST API queries and database access patterns — reduced page load latency by 25–30%",
        "Delivered 5+ CI/CD-based production releases; collaborated in Agile/Scrum sprints with 100% on-time delivery",
      ],
    },
  ],
  projects: [
    {
      name: "visual-ai-pipeline-builder",
      title: "Visual AI Pipeline Builder",
      desc: "Node-based visual workflow editor for designing AI pipelines using DAGs",
      tech: ["React Flow", "Zustand", "FastAPI", "Python"],
      highlights: ["DAG cycle detection via DFS", "Dynamic template variable parsing", "Reusable BaseNode abstraction"],
      github: "#",
      live: "#",
    },
    {
      name: "one4u-platform",
      title: "One4U — Corporate Canteen Platform",
      desc: "Full-stack ordering system with real-time tracking & AI recommendations",
      tech: ["React.js", "Node.js", "MongoDB", "Socket.IO", "Chart.js"],
      highlights: ["Real-time order tracking via Socket.IO", "Admin dashboard with sales analytics", "GenAI-based food recommendations"],
      github: "#",
      live: "#",
    },
    {
      name: "realtime-chat-app",
      title: "Realtime Chat App",
      desc: "WebSocket messaging with online presence & secure authentication",
      tech: ["MERN", "Tailwind CSS", "Zustand", "JWT"],
      highlights: ["WebSocket real-time messaging", "Online presence indicators", "Environment-based deployment on Render"],
      github: "#",
      live: "#",
    },
    {
      name: "pneumobot",
      title: "Pneumobot",
      desc: "AI-powered pneumonia detection chatbot using LLMs",
      tech: ["Python", "TensorFlow", "Keras", "Gradio", "Gemini"],
      highlights: ["Trained on Kaggle chest-xray dataset", "Dynamic scoring for prompt vs Gemini routing", "Fine-tuned on Google Colab"],
      github: "#",
    },
  ],
  education: [
    { degree: "B.Tech — Information Technology", school: "Maharaja Surajmal Institute of Technology, New Delhi", period: "2022-2026", grade: "CGPA: 7.6/10" },
    { degree: "Class XII (CBSE)", school: "Spring Meadows Public School", period: "2021", grade: "84%" },
    { degree: "Class X (CBSE)", school: "Spring Meadows Public School", period: "2019", grade: "90%" },
  ],
  achievements: [
    "Organizing Committee Member — 2nd Int'l Conference on AI & Applications, MSIT (Springer)",
    "Completed 6-week hands-on Generative AI training — built Pneumobot",
  ],
  blogs: [
    {
      title: "Why DAG Validation Matters in Pipeline Builders",
      slug: "dag-validation-pipeline-builders",
      tag: "architecture",
      date: "2026-02-15",
      readTime: "5 min",
      excerpt: "How cycle detection prevents broken AI workflows — and why every visual pipeline editor needs it.",
      content: [
        { type: "paragraph", text: "When building visual pipeline editors, users drag and drop nodes to create workflows. Behind the scenes, these workflows form Directed Acyclic Graphs (DAGs). The 'acyclic' part is critical — a cycle means an infinite loop, and that means a broken pipeline." },
        { type: "heading", text: "The Problem" },
        { type: "paragraph", text: "Imagine a user connects Node A → Node B → Node C → Node A. Without validation, this circular dependency would cause the execution engine to loop forever. In production AI pipelines, this isn't just a bug — it's wasted compute, failed jobs, and frustrated users." },
        { type: "heading", text: "DFS-Based Cycle Detection" },
        { type: "code", lang: "javascript", text: "function hasCycle(nodes, edges) {\n  const visited = new Set();\n  const recursionStack = new Set();\n\n  function dfs(nodeId) {\n    visited.add(nodeId);\n    recursionStack.add(nodeId);\n\n    const neighbors = edges\n      .filter(e => e.source === nodeId)\n      .map(e => e.target);\n\n    for (const neighbor of neighbors) {\n      if (!visited.has(neighbor)) {\n        if (dfs(neighbor)) return true;\n      } else if (recursionStack.has(neighbor)) {\n        return true; // cycle detected\n      }\n    }\n\n    recursionStack.delete(nodeId);\n    return false;\n  }\n\n  for (const node of nodes) {\n    if (!visited.has(node.id)) {\n      if (dfs(node.id)) return true;\n    }\n  }\n  return false;\n}" },
        { type: "paragraph", text: "The algorithm uses two sets: one for all visited nodes and one for nodes in the current recursion path. If we encounter a node that's already in the recursion stack, we've found a cycle." },
        { type: "heading", text: "Real-Time Validation UX" },
        { type: "paragraph", text: "In the Visual AI Pipeline Builder, I run this check every time an edge is added. If a cycle is detected, the edge is rejected with a visual error — the connection line turns red and a toast notification explains why. This gives users instant feedback without breaking their flow." },
        { type: "heading", text: "Takeaway" },
        { type: "paragraph", text: "DAG validation isn't optional in pipeline builders — it's foundational. Without it, you're letting users build workflows that will fail at runtime. A simple DFS check at edge-creation time prevents hours of debugging down the line." },
      ],
    },
    {
      title: "Scaling WebSockets: Lessons from a Chat App",
      slug: "scaling-websockets-chat-app",
      tag: "real-time",
      date: "2026-01-20",
      readTime: "6 min",
      excerpt: "What I learned about connection management, presence tracking, and graceful reconnection while building a real-time chat app.",
      content: [
        { type: "paragraph", text: "Building a real-time chat app sounds straightforward — connect users via WebSockets, send messages back and forth. But once you move past the tutorial phase, the real challenges emerge: connection stability, presence accuracy, and scaling beyond a single server." },
        { type: "heading", text: "Connection Lifecycle Management" },
        { type: "paragraph", text: "WebSocket connections are fragile. Users switch tabs, lose Wi-Fi, or let their phones sleep. A production chat app needs to handle all of this gracefully. I implemented a heartbeat system — the server pings every 30 seconds, and if three consecutive pongs are missed, the connection is marked as dead." },
        { type: "code", lang: "javascript", text: "// Server-side heartbeat\nio.on('connection', (socket) => {\n  let missedPongs = 0;\n\n  const heartbeat = setInterval(() => {\n    if (missedPongs >= 3) {\n      clearInterval(heartbeat);\n      socket.disconnect(true);\n      return;\n    }\n    missedPongs++;\n    socket.emit('ping');\n  }, 30000);\n\n  socket.on('pong', () => {\n    missedPongs = 0;\n  });\n\n  socket.on('disconnect', () => {\n    clearInterval(heartbeat);\n  });\n});" },
        { type: "heading", text: "Online Presence That Doesn't Lie" },
        { type: "paragraph", text: "Showing a green dot next to a user's name is easy. Making it accurate is hard. The naive approach — toggle online/offline on connect/disconnect events — fails because disconnects aren't always clean. I added a debounce: when a user disconnects, I wait 5 seconds before broadcasting their offline status. If they reconnect within that window (common during network hiccups), no one notices they were gone." },
        { type: "heading", text: "Message Ordering & Delivery Guarantees" },
        { type: "paragraph", text: "Messages can arrive out of order, especially on flaky connections. Each message gets a server timestamp and a sequence number per conversation. The client sorts by sequence number, not arrival time. For delivery confirmation, I implemented a simple ack system — the server emits a 'delivered' event with the message ID once it's persisted to MongoDB." },
        { type: "heading", text: "Key Lessons" },
        { type: "paragraph", text: "1. Never trust the connection state — always verify with heartbeats. 2. Debounce presence changes to avoid flicker. 3. Use server-side ordering, not client-side arrival time. 4. Plan for reconnection from day one — it's not an edge case, it's the norm." },
      ],
    },
    {
      title: "CI/CD Pipelines That Actually Save Time",
      slug: "cicd-pipelines-save-time",
      tag: "devops",
      date: "2025-12-08",
      readTime: "4 min",
      excerpt: "Most CI/CD setups waste more time than they save. Here's how I built pipelines that actually speed things up.",
      content: [
        { type: "paragraph", text: "Every team has CI/CD. Not every team has CI/CD that actually makes them faster. I've seen pipelines that take 20 minutes to run, block merges for flaky tests, and deploy so slowly that developers batch changes to avoid the wait. Here's what I've learned about building pipelines that help instead of hinder." },
        { type: "heading", text: "The Speed Tax" },
        { type: "paragraph", text: "A slow pipeline is a hidden tax on every commit. If your pipeline takes 15 minutes, and your team pushes 20 times a day, that's 5 hours of cumulative wait time — every single day. Developers context-switch, lose focus, and start batching changes into larger (riskier) commits to avoid triggering the pipeline." },
        { type: "heading", text: "Parallelize Everything" },
        { type: "code", lang: "yaml", text: "# GitHub Actions — parallel jobs\njobs:\n  lint:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci --cache .npm\n      - run: npm run lint\n\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci --cache .npm\n      - run: npm test -- --coverage\n\n  build:\n    runs-on: ubuntu-latest\n    needs: [lint, test]\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci --cache .npm\n      - run: npm run build" },
        { type: "paragraph", text: "Lint and test run in parallel. Build only starts after both pass. This alone cut our pipeline from 12 minutes to 6. Adding npm caching shaved off another minute." },
        { type: "heading", text: "Fail Fast, Fix Fast" },
        { type: "paragraph", text: "Order your pipeline stages by speed: lint first (seconds), unit tests next (seconds to minutes), integration tests last (minutes). If there's a syntax error, you know in 10 seconds instead of waiting for the full test suite. I also added Slack notifications for failures — the person who pushed gets a DM within seconds." },
        { type: "heading", text: "The Result" },
        { type: "paragraph", text: "After optimizing: lint + test in parallel (90 seconds), build (2 minutes), deploy to preview (1 minute). Total: under 4 minutes from push to preview URL. Developers push smaller commits more often because the feedback loop is tight. Fewer merge conflicts, fewer rollbacks, happier team." },
      ],
    },
  ],
};

export const ASCII_NAME = `
 ██████╗ ██╗  ██╗ █████╗ ██╗   ██╗██╗   ██╗ █████╗
 ██╔══██╗██║  ██║██╔══██╗██║   ██║╚██╗ ██╔╝██╔══██╗
 ██████╔╝███████║███████║██║   ██║ ╚████╔╝ ███████║
 ██╔══██╗██╔══██║██╔══██║╚██╗ ██╔╝  ╚██╔╝  ██╔══██║
 ██████╔╝██║  ██║██║  ██║ ╚████╔╝    ██║   ██║  ██║
 ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝  ╚═══╝     ╚═╝   ╚═╝  ╚═╝`;
